// This file was generated by README.org, read the solution from the source to get the link to the problem
function hurdleRace(k, height) {
    // Write your code here
  let maximum = height.reduce((max, element) => {
    if(element > max) return element;
    return max;
  });

  let numPotions = (maximum > k) ? (maximum - k) : 0;
  return numPotions;
}
